### ISSUE TITLE
Docmentation and Link on expandjs.com for `mat-shell`

### ISSUE THREAD

**Issue by ahmed-masud** [expandjs/mat-shell#1]
Seems to be missing for `mat-shell` ... Are you phasing this element out?

**Comment by Pupix** [comment]
Yep, forgot to update the `readme`. We are in the works of deprecating this element and we are replacing it with [mat-drawer-panel](https://github.com/expandjs/mat-drawer-panel).

`mat-shell`'s original purpose is no longer needed (managing app settings, main layout and what not), as time passed we have split these behaviors in different elements. (like `mat-settings` and `mat-drawer-panel`)
